version: "1.0"
info:
  model: int-scaffold
packages:
- name: Git3SeptProject
  gitServerName: GithubOrigin
  gitUrl: https://github.com/Munatri
  gitUsername: Munatri
  gitBranch: main
- name: CachingGitPackage
  gitServerName: GithubOrigin
  gitUrl: https://github.com/Munatri
  gitUsername: Munatri
  gitBranch: main
services:
- serviceName: project.git3sept.integrations:t2
  packages:
  - name: Git3SeptProject
    version: "1.0"
  - name: CachingGitPackage
    version: 10.15.0.0.674
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.1.0.0.2065
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2065
- serviceName: project.git3sept.referencedata:r1
  packages:
  - name: Git3SeptProject
    version: "1.0"
  - name: CachingGitPackage
    version: 10.15.0.0.674
